name: build

env:
  Configuration: Release
  ContinuousIntegrationBuild: true

on:
  pull_request:
    branches: ["master"]
  push:
    branches: ["master"]

jobs:
  build:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v3
      - name: Setup .NET
        uses: actions/setup-dotnet@v2
        with:
          dotnet-version: 8.0.x
      - name: Build
        run: ./build.ps1 Compile
      - name: Lint Check
        run: ./build.ps1 LintCheck --skip Compile
      - name: Unit Test
        run: ./build.ps1 RunUnitTests --skip LintCheck
      - name: Mutation Test
        run: ./build.ps1 RunMutationTests --skip RunUnitTests
        env:
          STRYKER_DASHBOARD_API_KEY: ${{ secrets.STRYKER_DASHBOARD_API_KEY }}