name: CI Workflow

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      DOTNET_SKIP_FIRST_TIME_EXPERIENCE: 1
      DOTNET_CLI_TELEMETRY_OPTOUT: 1

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Setup .NET
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '8.x' # Adjust to the .NET version you need

      - name: Install .NET tools
        run: |
          dotnet tool install -g dotnet-format
          dotnet tool install -g dotnet-stryker

      - name: Add .NET tools to PATH
        with:
          ACTIONS_ALLOW_UNSECURE_COMMANDS=true
        # run: echo "::add-path::$(dotnet tool path)"

      - name: Run PowerShell Script
        run: |
          pwsh -file ./build.ps1 -Task Compile
          pwsh -file ./build.ps1 -Task LintCheck
          pwsh -file ./build.ps1 -Task RunUnitTests
          pwsh -file ./build.ps1 -Task RunMutationTests
        shell: pwsh
